### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by CUR5EDFLVME** [shaffe-fr/flow-filezilla#2]
Flow Launcher version: 1.18.0
OS Version: 22631.3880
IntPtr Length: 8
x64: True

Python Path: C:\Users\cur5e\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Users\cur5e\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 08/02/2024 18:31:52
Exception:
System.IO.InvalidDataException: '"C:\Program Files\FileZilla FTP Client\"' is not recognized as an internal or external command,
operable program or batch file.
node:internal/errors:857
  const err = new Error(message);
              ^

Error: Command failed: "C:\Program Files\FileZilla FTP Client\" --site "0/zrtds.com"
'"C:\Program Files\FileZilla FTP Client\"' is not recognized as an internal or external command,

operable program or batch file.

    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at connect (file:///C:/Users/cur5e/AppData/Roaming/FlowLauncher/Plugins/FileZilla-1.0.2/dist/api.js:37:5)
    at Object.connect (file:///C:/Users/cur5e/AppData/Roaming/FlowLauncher/Plugins/FileZilla-1.0.2/dist/index.js:66:5)
    at Flow.run (C:\Users\cur5e\AppData\Roaming\FlowLauncher\Plugins\FileZilla-1.0.2\node_modules\flow-launcher-helper\lib\index.js:102:43)
    at file:///C:/Users/cur5e/AppData/Roaming/FlowLauncher/Plugins/FileZilla-1.0.2/dist/index.js:68:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(131) [Uint8Array] [
       39,  34,  67,  58,  92,  80, 114, 111, 103, 114,  97, 109,
       32,  70, 105, 108, 101, 115,  92,  70, 105, 108, 101,  90,
      105, 108, 108,  97,  32,  70,  84,  80,  32,  67, 108, 105,
      101, 110, 116,  92,  34,  39,  32, 105, 115,  32, 110, 111,
      116,  32, 114, 101,  99, 111, 103, 110, 105, 122, 101, 100,
       32,  97, 115,  32,  97, 110,  32, 105, 110, 116, 101, 114,
      110,  97, 108,  32, 111, 114,  32, 101, 120, 116, 101, 114,
      110,  97, 108,  32,  99, 111, 109, 109,  97, 110, 100,  44,
       13,  10, 111, 112,
      ... 31 more items
    ]
  ],
  pid: 14856,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(131) [Uint8Array] [
     39,  34,  67,  58,  92,  80, 114, 111, 103, 114,  97, 109,
     32,  70, 105, 108, 101, 115,  92,  70, 105, 108, 101,  90,
    105, 108, 108,  97,  32,  70,  84,  80,  32,  67, 108, 105,
    101, 110, 116,  92,  34,  39,  32, 105, 115,  32, 110, 111,
    116,  32, 114, 101,  99, 111, 103, 110, 105, 122, 101, 100,
     32,  97, 115,  32,  97, 110,  32, 105, 110, 116, 101, 114,
    110,  97, 108,  32, 111, 114,  32, 101, 120, 116, 101, 114,
    110,  97, 108,  32,  99, 111, 109, 109,  97, 110, 100,  44,
     13,  10, 111, 112,
    ... 31 more items
  ]
}

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteResultAsync(JsonRPCResult result) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 117
   at Flow.Launcher.Core.Plugin.JsonRPCPluginBase.<>c__DisplayClass18_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPluginBase.cs:line 89
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by shaffe-fr** [comment]
Hi looks like the path to Filezilla.exe is invalid. The path is only linking to the parent directory, the .exe is missing. Did you change anything in the settings ?

**Comment by CUR5EDFLVME** [comment]
Hello, idk, I never changed anything. I forgot to say that the plugin sorta works. You can see the fz servers, but when you try to connect to any of them, the crash is happening. 
<img width="683" alt="explorer_kPCOHhN0ro" src="https://github.com/user-attachments/assets/dc650a4d-1d44-4a78-b297-8da5b9f92d38">
<img width="709" alt="Flow Launcher_JcsuM2QwCT" src="https://github.com/user-attachments/assets/81e1831b-8207-4762-a247-c5e311ce7a09">

I don' really understand what's happened, but i reinstalled the plugin, restarted pc/flow launcher a number of times, I'm not sure what exactly fixed my problem and after some time it just fixed itself somehow. Sorry for bothering you, thank you for your work. The issue is fixed, i guess.

**Comment by shaffe-fr** [comment]
Hi, I'm glad the issue fixed itself! I'll have a look, I think I have enough info.
